### ISSUE TITLE
feat: allow native backup

### ISSUE THREAD

**Issue by castdrian** [ImageingApp/Imageing#56]
this requires cleaning up the local settings storage (which is a mess), since due to the managed workflow allowing both iCloud and Google backup natively is highly inconvenient to do, a simple encrypted import/export jumperio with google drive should solve the settings sync

**Comment by castdrian** [comment]
follow up to this, it would appear that iCloud backups by default support AsyncStorage and require no further manual configuaration, which sounds like it would probably best to make a manifest patch for android (puke) to enable google's native backup and restore as well

**Comment by thehairy** [comment]
expo W
