### ISSUE TITLE
feat: update suggestion

### ISSUE THREAD

**Issue by thehairy** [ImageingApp/Imageing#57]
When the app is started, the version should be checked against the latest release.
If a new version was released, a popup with the suggestion to update should be displayed.
When dismissed, the state gets saved and the popup only gets shown again, when a major was released.

**Comment by castdrian** [comment]
google has native api's for that, should be solvable with a single module that is invoked on launch
![image](https://user-images.githubusercontent.com/22133246/216318611-b5bfef86-5c68-4198-8308-e4e3d3c6b05f.png)

**Comment by castdrian** [comment]
this package specifically targets both OS's native api's
https://github.com/SudoPlz/sp-react-native-in-app-updates
