### ISSUE TITLE
feat: attach build artifacts to release

### ISSUE THREAD

**Issue by twisttaan** [ImageingApp/Imageing#58]
https://github.com/ImageingApp/Imageing/blob/main/.github/workflows/publish-semantic-release.yml should matrix build the app for iOS and android and attach the results

**Comment by castdrian** [comment]
ideally but can't do ios build without credentials, also each build workflow run produces an artifact already so there isn't really much reason to attach them to release as well since the versioning is out of sync at the moment

**Comment by castdrian** [comment]
yes I'm aware of how to supply the credentials, the issue at hand is that we do not have any

**Comment by castdrian** [comment]
gotta get that discussion going with @thehairy , I do however very much agree that semantic release should be merged with the eas build because the versioning needs to be in sync

**Comment by thehairy** [comment]
> 

Getting the actual account isn't that much of a problem, its more of a "Dont want to" cuz its work atm. kekw

**Comment by thehairy** [comment]
also I dont have an up to date iPhone to test hehe

**Comment by thehairy** [comment]
but feel free to join back on the discord so we can include you again :P
